### PR TITLE
Unregistered elderly bug

### LINKED ISSUE #140: [PE-D] Able to assign tasks to unregistered elderly
The user is able to assign an Elderly who is not in the list to a particular task. This could lead to confusion for the user.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: rushilramesh/ped#5

### LINKED ISSUE #156: [PE-D] addTask allows users to indicate elderly names that do not exist in NurseyBook
The user is able to add an invalid elderly name(i.e A name that has not been added to NurseryBook) to a task, as shown in the screenshot below. 
Steps to reproduce:
1. addTask desc/check insulin date/2021-10-29 time/23:00 en/Notaneldery

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: amzhy/ped#4

### LINKED ISSUE #161: [PE-D] editTask allows users to change valid elderly name to invalid ones
Steps to reproduce: 
1. addElderly en/John a/80 g/M r/90
2. addTask en/John desc/washdate date/2021-09-25 time/23:22
3. editTask 2 en/NotanElderly

Using the editTask command, a user is able to change a valid name of an elderly(John) to an invalid name that does not exist in NurseyBook.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: amzhy/ped#5

### LINKED ISSUE #197: [PE-D] Deleting elderly does not remove all traces of his name
steps to reproduce:
1. addElderly en/John Doe a/40 g/M r/53 nn/John Beckham rs/Father p/98765432 e/mary@example.com t/friends t/owesMoney
2. addTask en/John Doe desc/wash date/2021-10-29 time/19:20
3. deleteElderly 1

The elderly is related to the task, assuming the task is meant to be completed for that elderly, but when the elderly is deleted, the tag with his name remains in the task as shown.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: amzhy/ped#19

### LINKED ISSUE #198: [PE-D] Editing an elderly's name does not update all instances of his name in the app
steps to reproduce:

1. addElderly en/John Doe a/40 g/M r/53 nn/John Beckham rs/Father p/98765432 e/mary@example.com t/friends t/owesMoney
2. addTask en/John Doe desc/wash date/2021-10-29 time/19:20
3. editElderly 1 en/Joe

The elderly is related to the task, assuming the task is meant to be completed for that elderly, but when the elderly's name is edited, the tag with his initial name:John Doe still remains in the task as shown.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: amzhy/ped#20

### PR DESCRIPTION
**Pull request by Superbestron**
1. `AddTaskCommand` requires added elderly name to be first registered in NurseyBook. Fixes #156 
2. `EditTaskCommand` requires new edited elderly name to be first registered in NurseyBook. Fixes #140 Fixes #161
3. `EditCommand` updates all tasks containing the name of the elderly to edit with the new elderly name. Fixes #198 
4. `DeleteCommand` deletes all occurrences of the name of the elderly for tasks that contain the specfied elderly name in the command. Fixes #197

### CODE REVIEW

File: src/main/java/nurseybook/commons/core/Messages.java [hunk 1]
```diff
@@ -18,5 +18,7 @@
     public static final String MESSAGE_DUPLICATE_TASK = "This task already exists in the nursey book. \n"
             + "Hint: If you want to change the recurrence of a task, edit that specific task directly.";
     public static final String MESSAGE_NO_CHANGES = "Fields entered are the same as before.";
+    public static final String MESSAGE_NO_SUCH_ELDERLY = "Some of the elderly names are not found in our database.\n"
+            + "Please make sure all elderly names typed are already added into our database.";
```
Comment (CraveToCode) [inline src/main/java/nurseybook/commons/core/Messages.java:22]: Perhaps change `found in our database` to `found in our elderly database`? Just to avoid any ambiguity. Also changing `our` to `your` would be more you-centric language.

**Review by CraveToCode — CHANGES_REQUESTED** [review]
Changes LGTM! Just a minor note for the error message output.

File: src/main/java/nurseybook/commons/core/Messages.java (hunk 1 above)
Comment (Superbestron) [reply src/main/java/nurseybook/commons/core/Messages.java]: Great idea!

**Review by CraveToCode — APPROVED** [review]
LGTM!
