### PR TITLE
Add/Edit task duplicate bug

### LINKED ISSUE #137: [PE-D] Able to add duplicate Tasks
The user is able to add duplicate tasks, perhaps could occur if they copy-pasted their command. This could lead to unwanted data in the task list

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: rushilramesh/ped#4

### PR DESCRIPTION
**Pull request by Superbestron**
Fixes #137, #148, #155 
Also fix bug in test cases FindTaskCommandTest and EditTaskCommandTest

### CODE REVIEW

File: src/main/java/seedu/address/model/task/Task.java [hunk 1]
```diff
@@ -447,6 +447,19 @@ public boolean isPastCurrentDateAndRecurringTask() {
         return DateTime.isOverdue(this.dateTime) && recurrence.isRecurring();
     }
 
+    /**
+     * Returns true if both tasks have the same description.
+     * This defines a weaker notion of equality between two tasks.
+     */
+    public boolean isSameTask(Task otherTask) {
```
Comment (nicole-luo-exe) [inline src/main/java/seedu/address/model/task/Task.java:454]: We allow multiple tasks with same descriptions. But date, time and description cannot be all the same. Different recurrences still considered "same task" since no point in a daily/weekly/monthly task of the same date time to exist at once.

Comment (nicole-luo-exe) [reply src/main/java/seedu/address/model/task/Task.java:454]: I was thinking maybe we could have another error message for duplicate tasks with different recurrences- maybe append the current MESSAGE_DUPLICATE_TASK with a suggestion to edit the task directly? I feel this would benefit user experience.

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 import static java.util.Objects.requireNonNull;
 import static seedu.address.commons.core.Messages.MESSAGE_INVALID_TASK_DATETIME_FOR_RECURRING_TASK;
+import static seedu.address.logic.commands.AddTaskCommand.MESSAGE_DUPLICATE_TASK;
```
Comment (nicole-luo-exe) [inline src/main/java/seedu/address/logic/commands/EditTaskCommand.java:5]: I think maybe we should move these to commons->core->messages?

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java [hunk 3]
```diff
@@ -83,6 +84,10 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_INVALID_TASK_DATETIME_FOR_RECURRING_TASK);
         }
 
+        if (!taskToEdit.isSameTask(editedTask) && model.hasTask(editedTask)) {
```
Comment (nicole-luo-exe) [inline src/main/java/seedu/address/logic/commands/EditTaskCommand.java:87]: Could we also throw an error if taskToEdit is the same as edited task- "No changes made"? For this equality use equals() instead of isSameTask() since changing recurrence is still a change.

**Review by nicole-luo-exe — CHANGES_REQUESTED** [review]
Looks good! Just a few suggestions

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java (hunk 3 above)
Comment (Superbestron) [reply src/main/java/seedu/address/logic/commands/EditTaskCommand.java:92]: Throws MESSAGE_NO_CHANGE command exception now

File: src/main/java/seedu/address/logic/commands/EditTaskCommand.java (hunk 2 above)
Comment (Superbestron) [reply src/main/java/seedu/address/logic/commands/EditTaskCommand.java]: Moved!

File: src/main/java/seedu/address/model/task/Task.java (hunk 1 above)
Comment (Superbestron) [reply src/main/java/seedu/address/model/task/Task.java:454]: Used isSameTask() to check if `Description`, `Date` and `Time` are the same for "same" tasks.
Appended suggestion as stated above.

**Review by nicole-luo-exe — APPROVED** [review]
LGTM! Thanks for making the changes.
