### PR TITLE
Fix bugs related to overdue tasks in PED

### LINKED ISSUE #154: [PE-D] Completing overdue task still shows that it is overdue
Overdue tasks still reflect as such after completion.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: rushilramesh/ped#10

### PR DESCRIPTION
**Pull request by xiongjya**
Previously, a limitation of displaying tasks as overdue did not take into account on whether the task is completed or not, which is handled in this pull request. 

Fixes #154

### CODE REVIEW

File: src/test/java/nurseybook/model/task/TaskIsNotOverduePredicateTest.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        TaskIsNotOverduePredicate predicate = new TaskIsNotOverduePredicate();
+
+        // one minute before current time -> is overdue -> returns false
+        LocalDateTime now = LocalDateTime.now().withSecond(0).withNano(0);
+        LocalDateTime past = now.minusMinutes(1);
+        String[] dateTime = past.toString().split("T");
+        String date = dateTime[0];
+        String time = dateTime[1].substring(0, 5);
+
+        Task overdueYasminEPhysio = new TaskBuilder(YASMINE_PHYSIO).withDateTime(date, time).build();
```
Comment (Superbestron) [inline src/test/java/nurseybook/model/task/TaskIsNotOverduePredicateTest.java:29]: i think there's a minor typo here!

**Review by Superbestron — CHANGES_REQUESTED** [review]

**Review by Superbestron — APPROVED** [review]
LGTM after the changes!
